on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - release
    types: [closed]

jobs:
  build-and-deploy:
    if: github.event_name != 'pull_request' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Terraform Init and Apply
        run: |
          cd terraform/frontend
          terraform init
          terraform apply -auto-approve

      - name: Wait for EC2 to be fully ready
        run: sleep 120

      - name: Get EC2 IP
        run: |
          cd terraform/frontend
          echo "--- Terraform Output (Raw) ---"
          terraform output
          echo "--- End Terraform Output (Raw) ---"
          IP=$(terraform output -raw ec2_public_ip 2>/dev/null)
          echo "Extracted IP: $IP"
          if [ $? -ne 0 ]; then
            echo "Error: Terraform output -raw ec2_public_ip failed. Exit code: $?"
            exit 1
          fi
          if [[ "$IP" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "EC2_IP=$IP" >> "$GITHUB_ENV"
            echo "EC2_IP set to: $IP"
          else
            echo "Error: Invalid IP extracted: $IP"
            exit 1
          fi

      - name: Debug GITHUB_ENV
        run: |
          echo "--- GITHUB_ENV Contents ---"
          cat $GITHUB_ENV
          echo "--- End GITHUB_ENV Contents ---"

      - name: Deploy Dockerized Frontend to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ env.EC2_IP }}
          port: 22
          username: ec2-user
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            docker stop frontend || true
            docker rm frontend || true
            docker pull karmpatel/vitefrontend:latest
            docker run -d --name frontend -p 80:80 karmpatel/vitefrontend:latest